branding:
  color: purple
  icon: move
description: 'Move stories on Shortcut.com'
inputs:
  shortcut_story_prefix:
    description: Shortcut prefix (default "sc")
    required: true
    default: 'sc'
  shortcut_target_state_id:
    description: The workflow state where the story should be moved to
    required: true
  shortcut_task_description:
    description: Will add a task with this description
    required: false
name: Shortcut Move Story
runs:
  main: dist/index.js
  using: node16
